sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jungyinl/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jungyinl/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: docker-react
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-595216857454"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET  
